/**
 * MonACT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.spilab.monact.models;

import com.google.android.gms.maps.model.LatLng;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

import io.swagger.annotations.*;


@ApiModel(description = "")
public class User {
  
  @SerializedName("uuid")
  private String uuid = null;
  @SerializedName("name")
  private String name = null;


  @SerializedName("age")
  private int age = 0;

  @SerializedName("genre")
  private int genre = 99; //0 male //1 female

  @SerializedName("location")
  private LatLng location = null;
  @SerializedName("address")
  private String address = null;

  @SerializedName("postalAddress")
  private String postalAddress = null;

  @SerializedName("phone")
  private Integer phone = null;
  @SerializedName("state")
  private Boolean state = null;
  @SerializedName("activityTime")
  private Long activityTime = null;

  @SerializedName("healthParams")
  private ArrayList<UserHealth> heathParams = null;

  @SerializedName("idRequest")
  private Integer idRequest=null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }


  @ApiModelProperty(value = "")
  public int getAge() {
    return age;
  }
  public void setAge(int age) {
    this.age = age;
  }

  @ApiModelProperty(value = "")
  public int getGenre() {
    return genre;
  }
  public void setGenre(int genre) {
    this.genre = genre;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public LatLng getLocation() {
    return location;
  }
  public void setLocation(LatLng location) {
    this.location = location;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPhone() {
    return phone;
  }
  public void setPhone(Integer phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getState() {
    return state;
  }
  public void setState(Boolean state) {
    this.state = state;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getActivityTime() {
    return activityTime;
  }
  public void setActivityTime(Long activityTime) {
    this.activityTime = activityTime;
  }


  @ApiModelProperty(value = "")
  public ArrayList<UserHealth> getHealtParams() {
    return heathParams;
  }
  public void setHeathParams(ArrayList<UserHealth> heathParams) {
    this.heathParams = heathParams;
  }

  public Integer getIdRequest() {
    return idRequest;
  }

  public String getPostalAddress() {
    return postalAddress;
  }

  public void setPostalAddress(String postalAddress) {
    this.postalAddress = postalAddress;
  }

  public void setIdRequest(Integer idRequest) {
    this.idRequest = idRequest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (this.uuid == null ? user.uuid == null : this.uuid.equals(user.uuid)) &&
        (this.name == null ? user.name == null : this.name.equals(user.name)) &&
        (this.location == null ? user.location == null : this.location.equals(user.location)) &&
        (this.address == null ? user.address == null : this.address.equals(user.address)) &&
        (this.phone == null ? user.phone == null : this.phone.equals(user.phone)) &&
        (this.state == null ? user.state == null : this.state.equals(user.state)) &&
        (this.activityTime == null ? user.activityTime == null : this.activityTime.equals(user.activityTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.location == null ? 0: this.location.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.activityTime == null ? 0: this.activityTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  activityTime: ").append(activityTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
