/**
 * MonACT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.spilab.monact.resources;


import android.content.Context;
import com.spilab.monact.models.Alert;
import com.spilab.monact.responses.AlertResponse;
import com.spilab.monact.services.MQTTService;
import com.spilab.monact.utils.MqttClient;
import com.spilab.monact.utils.NotificationUtils;
import org.eclipse.paho.client.mqttv3.MqttException;
import java.io.UnsupportedEncodingException;


public class AlertResource {

    private Context context;
    private MqttClient client;

    private AlertResponse alertResponse;

    public AlertResource(Context context) {
        this.context = context;
        client = new MqttClient();
    }

    public Exception executeMethod(AlertResponse response) throws MqttException, UnsupportedEncodingException {

        alertResponse = response;

        switch (response.getMethod()) {
            case "postAlert":
                postAlert(response.getParams().getalert());
                break;
            default:
                client.publishMessage(MQTTService.getClient(), "Error: Not Found Method", 1, alertResponse.getSender());
                return new Exception("Not found method.");
        }
        return null;
    }

    /**
     * Sends an alert to the users.
     *
     * @param alert
     * @return String
     */
    public void postAlert(Alert alert) {

        NotificationUtils.showNotification(alert.getTitle(), alert.getDescription(), context, android.R.drawable.ic_dialog_alert);

    }


}
